### PR TITLE
Move VTK-only code to VTK module

### PR DESCRIPTION
**Pull request by JochenJankowai**

### CODE REVIEW

**Comment by JochenJankowai** [comment]
Can someone please point out why the Jenkins build fails?

**Comment by ResearchDaniel** [comment]
Might be that no warnings are accepted?
Check the Clang warnings in the menu to the left
http://jenkins.inviwo.org:8080/job/modules/job/feature%252Fmove-vtk-only-code-to-vtk-module/

**Comment by r-englund** [comment]
Ttk warnings due to updated qt.

**Comment by JochenJankowai** [comment]
Thanks @ResearchDaniel, I have submitted pull requests to ttk to fix the warnings.

**Comment by r-englund** [comment]
rebased

**Pull request closed without merging**
