### PR TITLE
Make module depend on VTK module and scrap VTK related cmake commands

### PR DESCRIPTION
**Pull request by JochenJankowai**

### CODE REVIEW

**Comment by martinfalk** [comment]
I am assuming that the idea is to move the vtk module to modules as well in the near future...

**Comment by r-englund** [comment]
> 
> 
> I am assuming that the idea is to move the vtk module to modules as well in the near future...

Yes, I am looking into moving my code out of that module (it is a "works only on my data" type of code :) )

**Comment by petersteneteg** [comment]
Still should move it out of reseach-dev first...

**Comment by r-englund** [comment]
> 
> 
> Still should move it out of reseach-dev first...

I want to move my stuff first

**Comment by petersteneteg** [comment]
Could copy it I guess

**Comment by r-englund** [comment]
> 
> 
> Could copy it I guess

I have moved it now

**Comment by r-englund** [comment]
I've cherry-picked this into a branch where I am moving the   VTK module from research-dev, will be in a PR today or tomorrow

**Comment by r-englund** [comment]
Cherry-picked into #30

**Pull request closed without merging**
